version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bankverte_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bankverte
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bankverte_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: bankverte_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - bankverte_net
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: bankverte_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankverte
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - bankverte_net

networks:
  bankverte_net:
    driver: bridge

volumes:
  db_data:
